In [3]:
#imports 
import numpy as np 
import math as m
import pandas as pd
import gates as g

pi =np.pi 


In [4]:
g.CNOT

AttributeError: module 'gates' has no attribute 'CNOT'

Opperators defined

Hadamard  $\hat{H} = \frac{1}{\sqrt{2}}\begin{pmatrix} 1 &1 \\ 1 & -1\end{pmatrix}$ there exists two different Hadmard gates in our optical set up. For polariztion it is the polarizer and for the path it is the beamcube
Beamcube $\hat{BS} = \frac{1}{\sqrt{2}}\begin{pmatrix} 1 &i \\ i & 1\end{pmatrix}$ Polarizer $\hat{P} = \begin{pmatrix} cos^2 \theta & cos \theta sin \theta \\
cos \theta sin \theta & sin^2 \theta \end{pmatrix}$

Identity $\hat{I} = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix}$ 
Half Waveplate $\hat W = \begin{pmatrix} cos 2 \theta & sin2 \theta \\ sin 2 \theta & -cos 2 \theta  \end{pmatrix}$ 



In [ ]:

I = np.array([[1,0],[0,1]])

def W_4 (theta_0,theta_1):
    error = 10**-10
    w_0 =np.sin(2*theta_0)
    w_1 = np.sin(2*theta_1)
    #This accounts for rounding errors
    if (w_0<error):
        w_0 = 0
    if (w_1<error):
        w_1 = 0
    cos_0=np.cos(2*theta_0)
    cos_1=np.cos(2*theta_1)
    if (cos_0<error):
        cos_0 = 0
    if (cos_1<error):
        cos_1 = 0
    w = np.array([[w_0, cos_0,0,0],
                  [cos_0,-w_0,0,0],
                  [0,0,w_1,cos_1],
                  [0,0,cos_1 ,-w_1]])
    return w

def W_2 (theta_0):
    w_0 =np.sin(theta_0)
    w_1 =np.cos(theta_0)
    #This accounts for rounding errors
    if (w_0<10**-15):
        w_0 = 0
    w = np.array([[2*w_1,2*w_0],[2*w_0,2*w_1]])
    return w

def P(theta):
    sin = np.sin(theta)
    cos = np.cos(theta)
    if (sin<10**-15):
        sin = 0
    if (cos<10**-15):
        cos = 0
    
    P = np.array([[cos**2 , cos*sin],[cos*sin, sin**2]])
    return P

BS = (1/m.sqrt(2))*np.array([[1,-1j],[-1j,1]])


Pauli matrices

The Pauli X gate is the mirror opperator $\sigma_X = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}$

Pauli Y  $ \sigma_Y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}$

Pauli Z $ \sigma_Z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}$

In [ ]:
def M_theta(theta):
    sin = np.sin(theta)
    cos = np.cos(theta)
    if (sin<10**-10):
        sin = 0
    if (cos<10**-10):
        cos = 0
    
    P = np.array([[cos, -sin],[sin, cos]])
    return P

In [ ]:
ket_0_T = np.array([1,0])
ket_1_T = np.array([0,1])

ket_01_T =np.kron(ket_0_T,ket_1_T)

ket_intial_T = (-1/np.sqrt(2))*np.array([1,-1,0,0])


Incomming beam is in the x direction in out set up and set in the vertal polariztion 

$\ket{x,V} = \begin{pmatrix} 1 \\ 0 \end{pmatrix} \otimes \begin{pmatrix} 0 \\ 1 \end{pmatrix}$

Incomming photon after Crystal (parametric down conversion) 
$\ket{\phi_x } $ 

Going though the pololarizer 
$\hat P\ket{\phi_x} \rightarrow \frac{-1}{ \sqrt{2}} (\ket{H} -\ket{V})$

Applying $\hat I \otimes \hat P$ as we are not changing the path but the polarization

In [ ]:
ket_v = ket_1_T
theta_k = -pi/4
ket_theta= np.array([np.cos(theta_k),np.sin(theta_k)])
p = np.outer(ket_theta,ket_theta)

ket_p = np.matmul(p,ket_v)

ket_p = np.kron(ket_0_T,ket_p)

In [ ]:
M_one =np.array([[1,-1,],[1,1]])
M_two = np.array([[0,1j],[-1j,0]])
Bs_idea = np.kron(M_one,M_two)
#print(np.matmul(W_4(0,pi/4),np.kron(Z,M)))
print(W_4(pi/4,0))



[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]]


In [ ]:
def check(answer):
    if()    

In [ ]:
ket_a = np.matmul(np.kron(BS,Z),ket_p)
#print(np.kron(BS,I))
print("After  beam cube: ",ket_a, '\n')
ket_b = np.matmul(np.kron(I,I),ket_a)
print("After Mirror One: ",ket_b,'\n')
ket_c = np.matmul(W_4(0,pi/4),ket_b)
print("After waveplate: ", ket_c,'\n')
ket_d = np.matmul(np.kron(I,I),ket_c)
print("After Mirror two: ", ket_d,'\n')
ket_e = np.matmul(np.kron(BS,Z),ket_d)
print("After Bs: ", ket_e,'\n')
#M_theta(pi/4)


After  beam cube:  [-0.35355339+0.j         -0.35355339+0.j          0.        +0.35355339j
  0.        +0.35355339j] 

After Mirror One:  [-0.35355339+0.j         -0.35355339+0.j          0.        +0.35355339j
  0.        +0.35355339j] 

After waveplate:  [-0.35355339+0.j         -0.35355339+0.j          0.        +0.35355339j
  0.        -0.35355339j] 

After Mirror two:  [-0.35355339+0.j         -0.35355339+0.j          0.        +0.35355339j
  0.        -0.35355339j] 

After Bs:  [0. +0.j  0.5+0.j  0. +0.5j 0. +0.j ] 



Beamsplitter - creates our second Qubit which is path dependent and also opperates 
We get 

$\ket{ \phi_0} = \frac{-1}{2}(\ket{a}+ i\ket{b})_x \otimes ( \ket{H} -\ket{V})_y$

In [ ]:
phi_0_path = -0.5*(ket_0_T + 1j*ket_1_T)
phi_0_polar =(ket_0_T - ket_1_T)
phi_0 = np.kron(phi_0_path,phi_0_polar)

In [ ]:
#trying the matrix guess and returning results for every possible waveplate combonation
def WavePlate_guess(guess):
    theta_0 = 2*pi
    theta_1 = pi/2
    angle = [0,pi/2,pi]
    M_tests = []
    for theta_0 in angle:
        for theta_1 in angle:
            M_tests.append({"theta_0":pi_text(theta_0) ,"theta_1": pi_text(theta_1), 
                            "matrix_GW": np.matmul(guess,W_4(theta_0,theta_1))}) 
                            #"matrix_WG" :np.matmul(W_4(theta_0,theta_1),guess)}
    return pd.DataFrame(M_tests) 
#WavePlate_guess(CNOT).iloc[:,3]


In [ ]:
#Targets

targets = np.array([[1,0,0,0],[0,-1,0,0],[0,0,1,0],[0,0,0,-1]])


we only apply the Beam splitter to the polarization

In [ ]:
#phi_3 = np.matmul(I_otimes_BS,phi_2)
#phi_3