In [12]:
#imports 
import numpy as np 
import math as m
import pandas as pd

#Im inporting the code from the other files.
#Scrolling and the choatic mess of having it in one file
# drove me up a wall plus I was using that code in more than one file
import gates as g
import checking

pi =np.pi 

In [13]:
print(g.CNOT)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]


In [14]:
gate = np.sqrt(2)*np.kron(g.BS,g.I)
print(np.matmul(g.CNOT,np.transpose(gate)))

[[1.+0.j 0.+0.j 0.-1.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.-1.j]
 [0.+0.j 0.-1.j 0.+0.j 1.+0.j]
 [0.-1.j 0.+0.j 1.+0.j 0.+0.j]]


In [15]:
mat = np.array([[-2,1,-2,0,0,0],[1,0,0,0,-1,1],[0,0,0,0,-1,0],[0,1,1,-1,0,0],[0,0,0,-1,-1,1]])
#print(mat)
mat_T =np.transpose(mat)
#print(mat_T)
print(np.matmul(mat_T,mat))

[[ 5 -2  4  0 -1  1]
 [-2  2 -1 -1  0  0]
 [ 4 -1  5 -1  0  0]
 [ 0 -1 -1  2  1 -1]
 [-1  0  0  1  3 -2]
 [ 1  0  0 -1 -2  2]]


In [16]:
print(np.matmul(g.BS,g.ket_H))

[0.        +0.70710678j 0.70710678+0.j        ]
